# Site settings
# SEO Title and description
# SoM email address
title: Azavea Summer of Maps
email: summerofmaps@azavea.com # currently unused
description: >- # this means to ignore newlines until "baseurl:"
  A 12-week fellowship where geospatial data analysis students work alongside experienced mentors to complete projects for nonprofit organizations.

# Fellowship settings
# What is the current year for the fellowship?
# What is the current session timeframe? (ie: Summer 2018)
# Is the fellowship in progress?
# What is the stage of the current fellowship?
# Only assign true to the current stage
fellowship:
  year: 2020
  timeframe: Summer 2020
  out_of_session:
    # if summer of maps has ended
    freeze: true
    # if summer of maps applications will be going out soon
    upcoming: false
  in_session:
    # if nonprofit/student applications at separate times
    nonprofit_signup: false
    nonprofit_review: false
    student_signup: false
    student_review: false
    student_announcement: false
    # if nonprofit/student applications at the same times
    applications_signup: false
    applications_review: false
    applications_announcements: false
    # if students are actively working
    fellowship_ongoing: false

# Student and Non-profit application links
# Define where the applications live
nonprofit_app_link: "https://azavea.forms.fm/2020-summer-of-maps-nonprofit-application/forms/7494"
student_app_link: "https://hire.withgoogle.com/public/jobs/azaveacom/view/P_AAAAAADAABpIvUZ6MpUYe-"

####
## DON'T EDIT BEYOND THIS LINE
####
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Establish project collections
# Establish project shortlist collections
collections:
  projects:
    output: true
    permalink: /:collection/:slug
  project-shortlist:
    output: true
    permalink: /projects/shortlist/:slug

# Define site defaults for post types
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "post" # automatically sets layout for projects
      is_project: true # automatically set is_post=true for all projects
      published: false # automatically sets all project as drafts
      page_class: "projects"
  - scope:
      path: ""
      type: "project-shortlist"
    values:
      layout: "post" # automatically sets layout for projects
      is_shortlist: true # automatically set is_shortlist=true for all project shortlist
      published: false # automatically sets all project as drafts
      page_class: "projects"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# sass settings
sass:
  sass_dir: _sass
  style: compressed

include:
  - _pages
  - _project-archive-years
  - _shortlist-archive-years

exclude:
  - .gitignore
  - .vagrant/
  - deployment/
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - scripts/
