version: '3'
services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - '4000:4000'
      - '35729:35729'
    environment:
      - JEKYLL_ENV=development
      - LANG=C.UTF-8
    command: serve --verbose --incremental --livereload --force_polling --host 0.0.0.0
